/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Hospital;

import Business.Enterprise.Enterprise;
import static Business.Enterprise.Enterprise.EnterpriseType.Hospital;
import Business.Hospital.Hospital;
import Business.Network.Network;
import Business.Organization.HospitalOrganization;
import Business.Organization.Organization;
import Business.QuickAssist;
import java.awt.CardLayout;
import java.awt.Color;
import java.util.Random;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sanka_001
 */
public class AddHospitals extends javax.swing.JPanel {

    JPanel userProcessContainer;
    QuickAssist system;
    Enterprise enterprise;
    Network network;
    double longitude;
    double latitude;

    /**
     * Creates new form AddHospitals
     */
    public AddHospitals(JPanel userProcessContainer, QuickAssist system, Enterprise enterprise, Network network) {
        initComponents();
        this.setBackground(Color.white);

        this.userProcessContainer = userProcessContainer;
        this.system = system;
        this.enterprise = enterprise;
        this.network = network;
        populateHospitalTable();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblHospital = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtHospitalName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtHospitalAddress = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnback = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtHospitalID = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtHospitalPhone = new javax.swing.JTextField();
        btnDelete = new javax.swing.JButton();
        lblName = new javax.swing.JLabel();
        lblAddress = new javax.swing.JLabel();
        lblID = new javax.swing.JLabel();
        lblPhone = new javax.swing.JLabel();

        tblHospital.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        tblHospital.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Hospital Name", "Hospital Address", "Hospital ID", "Hospital Phone"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblHospital);
        if (tblHospital.getColumnModel().getColumnCount() > 0) {
            tblHospital.getColumnModel().getColumn(0).setResizable(false);
            tblHospital.getColumnModel().getColumn(1).setResizable(false);
            tblHospital.getColumnModel().getColumn(2).setResizable(false);
            tblHospital.getColumnModel().getColumn(3).setResizable(false);
        }

        jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel1.setText("Hospital Name");

        txtHospitalName.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtHospitalName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtHospitalNameMouseExited(evt);
            }
        });
        txtHospitalName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtHospitalNameKeyPressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setText("Hospital Address");

        txtHospitalAddress.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtHospitalAddress.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtHospitalAddressMouseExited(evt);
            }
        });
        txtHospitalAddress.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtHospitalAddressKeyPressed(evt);
            }
        });

        btnAdd.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnback.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnback.setText("Back");
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel3.setText("Hospital ID");

        txtHospitalID.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtHospitalID.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtHospitalIDMouseExited(evt);
            }
        });
        txtHospitalID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtHospitalIDKeyPressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel4.setText("Hospital Phone");

        txtHospitalPhone.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtHospitalPhone.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtHospitalPhoneMouseExited(evt);
            }
        });
        txtHospitalPhone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtHospitalPhoneKeyPressed(evt);
            }
        });

        btnDelete.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        lblName.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblName.setText("  ");

        lblAddress.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblAddress.setText("  ");

        lblID.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblID.setText("  ");

        lblPhone.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblPhone.setText("  ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnback)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(66, 66, 66)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAdd)
                                .addGap(119, 119, 119)
                                .addComponent(btnDelete))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtHospitalAddress, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtHospitalName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtHospitalPhone, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtHospitalID, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblID, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(14, 14, 14)
                                        .addComponent(lblAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1042, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtHospitalName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblName))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtHospitalAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAddress))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtHospitalID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblID))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtHospitalPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPhone))))
                .addGap(126, 126, 126)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnback)
                    .addComponent(btnDelete))
                .addGap(50, 50, 50))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void getLocation(double x0, double y0, int radius) {
        Random random = new Random();

        // Convert radius from meters to degrees
        double radiusInDegrees = radius / 111000f;

        double u = random.nextDouble();
        double v = random.nextDouble();
        double w = radiusInDegrees * Math.sqrt(u);
        double t = 2 * Math.PI * v;
        double x = w * Math.cos(t);
        double y = w * Math.sin(t);

        // Adjust the x-coordinate for the shrinking of the east-west distances
        double new_x = x / Math.cos(y0);

        longitude = new_x + x0;
        latitude = y + y0;
    }


    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnbackActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        int count = 0;
        if (txtHospitalID.getText().trim().isEmpty()) {
            count++;
        }
        if (txtHospitalAddress.getText().trim().isEmpty()) {
            count++;
        }
        if (txtHospitalName.getText().trim().isEmpty()) {
            count++;
        }
        if (txtHospitalPhone.getText().trim().isEmpty()) {
            count++;
        }

        if (count > 0) {
            JOptionPane.showMessageDialog(null, "Please enter all the details", "Information", JOptionPane.ERROR_MESSAGE);
        }

        if ((txtHospitalPhone.getText().length() > 10)||(txtHospitalPhone.getText().length() < 10)) {
            JOptionPane.showMessageDialog(null, "Please enter only 10 digit phone number", "Information", JOptionPane.ERROR_MESSAGE);

        } else {

            getLocation(42.358544, -71.16394, 6000);
            for (Organization org : enterprise.getOrganizationDirectory().getOrganizationList()) {
                if (org instanceof HospitalOrganization) {
                    Hospital hospital = org.getHospitalDirectory().createHospital(txtHospitalName.getText(), txtHospitalAddress.getText(), Integer.parseInt(txtHospitalID.getText()), txtHospitalPhone.getText(), longitude, latitude);
                    populateHospitalTable();
                }
            }
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        int selectedRow = tblHospital.getSelectedRow();
        if (selectedRow >= 0) {
            Hospital hospital = (Hospital) tblHospital.getValueAt(selectedRow, 0);

            for (Organization org : enterprise.getOrganizationDirectory().getOrganizationList()) {
                if (org instanceof HospitalOrganization) {
                    org.getHospitalDirectory().deleteHospital(hospital);
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please select a row from the table to be deleted", "Information", JOptionPane.ERROR_MESSAGE);

        }
        populateHospitalTable();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void txtHospitalNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHospitalNameKeyPressed
        char percharacter = evt.getKeyChar();
        if (percharacter >= 65 && percharacter < 90 || percharacter >= 97 && percharacter <= 122 || percharacter == 32 || percharacter == 8) {
            lblName.setText("");
            txtHospitalName.setEditable(true);
            txtHospitalName.setBackground(Color.white);
        } else {
            evt.consume();
            lblName.setText("Hospital name can only be alphabetic");
            txtHospitalName.setEditable(false);
            txtHospitalName.setBackground(Color.yellow);
        }

    }//GEN-LAST:event_txtHospitalNameKeyPressed

    private void txtHospitalAddressKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHospitalAddressKeyPressed
        char percharacter = evt.getKeyChar();
        if (percharacter >= 65 && percharacter < 90 || percharacter >= 97 && percharacter <= 122 || percharacter == 32 || percharacter == 8 || percharacter >= 48 && percharacter < 58) {
            lblAddress.setText("");
            txtHospitalAddress.setEditable(true);
            txtHospitalAddress.setBackground(Color.white);
        } else {
            evt.consume();
            lblAddress.setText("Hospital address can only be alphabetic");
            txtHospitalAddress.setEditable(false);
            txtHospitalAddress.setBackground(Color.yellow);
        }
    }//GEN-LAST:event_txtHospitalAddressKeyPressed

    private void txtHospitalIDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHospitalIDKeyPressed
        int key = evt.getKeyCode();
        if ((key >= evt.VK_0 && key <= evt.VK_9) || (key >= evt.VK_NUMPAD0 && key <= evt.VK_NUMPAD9) || (key == evt.VK_BACK_SPACE)) {
            txtHospitalID.setEditable(true);
            txtHospitalID.setBackground(Color.white);
            lblID.setText("");
        } else {
            txtHospitalID.setEditable(false);
            txtHospitalID.setBackground(Color.yellow);
            lblID.setText("Please enter only numbers");
        }
    }//GEN-LAST:event_txtHospitalIDKeyPressed

    private void txtHospitalPhoneKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHospitalPhoneKeyPressed
        int key = evt.getKeyCode();
        if ((key >= evt.VK_0 && key <= evt.VK_9) || (key >= evt.VK_NUMPAD0 && key <= evt.VK_NUMPAD9) || (key == evt.VK_BACK_SPACE)) {
            txtHospitalID.setEditable(true);
            txtHospitalID.setBackground(Color.white);
            lblID.setText("");
        } else {
            txtHospitalID.setEditable(false);
            txtHospitalID.setBackground(Color.yellow);
            lblPhone.setText("Please enter only numbers");
        }
    }//GEN-LAST:event_txtHospitalPhoneKeyPressed

    private void txtHospitalPhoneMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtHospitalPhoneMouseExited
        txtHospitalPhone.setBackground(Color.white);
        lblPhone.setText("");
    }//GEN-LAST:event_txtHospitalPhoneMouseExited

    private void txtHospitalIDMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtHospitalIDMouseExited
        txtHospitalID.setBackground(Color.white);
        lblID.setText("");
    }//GEN-LAST:event_txtHospitalIDMouseExited

    private void txtHospitalAddressMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtHospitalAddressMouseExited
        txtHospitalAddress.setBackground(Color.white);
        lblAddress.setText("");
    }//GEN-LAST:event_txtHospitalAddressMouseExited

    private void txtHospitalNameMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtHospitalNameMouseExited
        txtHospitalName.setBackground(Color.white);
        lblName.setText("");
    }//GEN-LAST:event_txtHospitalNameMouseExited
    private void populateHospitalTable() {

        DefaultTableModel dtm = (DefaultTableModel) tblHospital.getModel();
        dtm.setRowCount(0);
        for (Organization org : enterprise.getOrganizationDirectory().getOrganizationList()) {
            if (org instanceof HospitalOrganization) {
                for (Hospital hospital : org.getHospitalDirectory().getHospitalList()) {
                    Object[] row = new Object[4];
                    row[0] = hospital;
                    row[1] = hospital.getAddress();
                    row[2] = hospital.getHospitalID();
                    row[3] = hospital.getPhone();

                    dtm.addRow(row);

                }
            }
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnback;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JTable tblHospital;
    private javax.swing.JTextField txtHospitalAddress;
    private javax.swing.JTextField txtHospitalID;
    private javax.swing.JTextField txtHospitalName;
    private javax.swing.JTextField txtHospitalPhone;
    // End of variables declaration//GEN-END:variables
}
