/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Hospital;

import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.HospitalOrganization;
import Business.Organization.Organization;
import Business.Organization.Organization.Type;
import Business.QuickAssist;
import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sanka_001
 */
public class AddOrganizationJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    QuickAssist system;
    Enterprise enterprise;
    Network network;
    Type type;

    /**
     * Creates new form AddOrganization
     */
    public AddOrganizationJPanel(JPanel userProcessContainer, QuickAssist system, Enterprise enterprise, Network network) {
        initComponents();
        this.setBackground(Color.white);
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        this.enterprise = enterprise;
        this.network = network;
        populateCombo();
        populateTable();
        txtOrganizationName.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        txtOrganizationName = new javax.swing.JTextField();
        btnDeleteOrg = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        cmbOrganization = new javax.swing.JComboBox();
        btnBack = new javax.swing.JButton();
        btnCreate = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblOrganizations = new javax.swing.JTable();
        lblStatus = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setText("Organization Name:");

        txtOrganizationName.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtOrganizationName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtOrganizationNameMouseExited(evt);
            }
        });
        txtOrganizationName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtOrganizationNameKeyPressed(evt);
            }
        });

        btnDeleteOrg.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnDeleteOrg.setText("Delete");
        btnDeleteOrg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteOrgActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel3.setText("Organization Type:");

        cmbOrganization.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        cmbOrganization.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbOrganizationActionPerformed(evt);
            }
        });

        btnBack.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnCreate.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnCreate.setText("Create");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        tblOrganizations.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        tblOrganizations.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Org Name", "Org Type"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblOrganizations);

        lblStatus.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblStatus.setText("                                                         ");

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setText("Add Organizations");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(23, 23, 23)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel2))
                            .addGap(49, 49, 49)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(cmbOrganization, 0, 249, Short.MAX_VALUE)
                                .addComponent(txtOrganizationName))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lblStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(109, 109, 109)
                            .addComponent(btnCreate)
                            .addGap(39, 39, 39)
                            .addComponent(btnBack)
                            .addGap(29, 29, 29)
                            .addComponent(btnDeleteOrg)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(380, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cmbOrganization, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtOrganizationName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblStatus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCreate)
                    .addComponent(btnBack)
                    .addComponent(btnDeleteOrg))
                .addGap(33, 33, 33))
        );
    }// </editor-fold>//GEN-END:initComponents
    private void populateCombo() {
        cmbOrganization.removeAllItems();
        String enterpriseType = enterprise.getEnterpriseType().getValue();
        for (Type type : Organization.Type.values()) {
            if (enterpriseType.equals("HospitalEnterprise")) {
                if (!(type.getValue().equals(Type.Mayor.getValue())) && !(type.getValue().equals(Type.SysAdmin.getValue())) && !(type.getValue().equals(Type.Doctor.getValue())) && !(type.getValue().equals(Type.DoctorAdmin.getValue())) && !(type.getValue().equals(Type.Drone.getValue())) && !(type.getValue().equals(Type.DroneWarehouseAdmin.getValue())) && !(type.getValue().equals(Type.Patient.getValue())) && !(type.getValue().equals(Type.SensorAdmin.getValue()))) {
                    cmbOrganization.addItem(type);
                }
            }
        }
    }

    private void populateTable() {
        DefaultTableModel dtm = (DefaultTableModel) tblOrganizations.getModel();
        dtm.setRowCount(0);
        for (Organization org : enterprise.getOrganizationDirectory().getOrganizationList()) {
            if (org instanceof HospitalOrganization) {
                Object[] row = new Object[3];
                row[0] = org;
                row[1] = org.getClass();
                row[2] = org.getOrganizationId();

                dtm.addRow(row);
            }

        }
    }


    private void btnDeleteOrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteOrgActionPerformed
        int selectedRow = tblOrganizations.getSelectedRow();
        if (selectedRow >= 0) {
            Organization org = (Organization) tblOrganizations.getValueAt(selectedRow, 0);
            enterprise.getOrganizationDirectory().deleteOrganization(org);
            populateTable();
        } else {
            JOptionPane.showMessageDialog(null, "Please select an entry from the table");
        }
    }//GEN-LAST:event_btnDeleteOrgActionPerformed

    private void cmbOrganizationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbOrganizationActionPerformed
        type = (Type) cmbOrganization.getSelectedItem();
        txtOrganizationName.setEditable(true);
    }//GEN-LAST:event_cmbOrganizationActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        int count = 0;
        if (txtOrganizationName.getText().trim().isEmpty()) {
            count++;
        }
        if (count > 0) {
            JOptionPane.showMessageDialog(null, "Please enter all the details", "Information", JOptionPane.ERROR_MESSAGE);
        } else {

            if (!txtOrganizationName.getText().trim().isEmpty()) {

                for (Organization org : enterprise.getOrganizationDirectory().getOrganizationList()) {
                    int flag = 0;
                    String orgName = txtOrganizationName.getText();
                    if ((type.getValue()).equals("Hospital")) {
                        flag = 1;
                        break;

                    }
                    if (flag == 0) {
                        enterprise.getOrganizationDirectory().createOrganization(type, orgName);
                        populateTable();
                    } else {
                        JOptionPane.showMessageDialog(null, "Already existing");
                    }

                }
            }
        }
        populateTable();
         JOptionPane.showMessageDialog(null, "Organization already exists", "Information", JOptionPane.INFORMATION_MESSAGE);
        
    }//GEN-LAST:event_btnCreateActionPerformed

    private void txtOrganizationNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtOrganizationNameKeyPressed
        // TODO add your handling code here:
        char percharacter = evt.getKeyChar();
        if (percharacter >= 65 && percharacter < 90 || percharacter >= 97 && percharacter <= 122 || percharacter == 32 || percharacter == 8) {
            lblStatus.setText("");
            txtOrganizationName.setEditable(true);
            txtOrganizationName.setBackground(Color.white);
        } else {
            evt.consume();
            lblStatus.setText("Organization name can only be alphabetic");
            txtOrganizationName.setEditable(false);
            txtOrganizationName.setBackground(Color.yellow);
        }

    }//GEN-LAST:event_txtOrganizationNameKeyPressed

    private void txtOrganizationNameMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtOrganizationNameMouseExited
        txtOrganizationName.setBackground(Color.white);
    }//GEN-LAST:event_txtOrganizationNameMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnDeleteOrg;
    private javax.swing.JComboBox cmbOrganization;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JTable tblOrganizations;
    private javax.swing.JTextField txtOrganizationName;
    // End of variables declaration//GEN-END:variables
}
