/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.HealthAssistantAdmin;

import UserInterface.HealthAssistantAdmin.ManageUserAccountJPanel;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.QuickAssist;
import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.JPanel;

/**
 *
 * @author sanka_001
 */
public class HealthAssistantWorkAreaJPanel extends javax.swing.JPanel {
    JPanel userProcessContainer;
    QuickAssist system;
    Enterprise enterprise;
    Organization organization;
    
    /**
     * Creates new form HealtAssistantWorkAreaJPanel
     */
    public HealthAssistantWorkAreaJPanel(JPanel userProcessContainer,Organization organization, QuickAssist system, Enterprise enterprise) {
        initComponents();
        this.setBackground(Color.white);
        this.userProcessContainer= userProcessContainer;
        this.system= system;
        this.enterprise=enterprise;
        this.organization= organization;
        System.out.println(enterprise.getOrganizationDirectory().getOrganizationList());
        String enterpriseType= enterprise.getEnterpriseType().getValue();
        System.out.println(enterpriseType);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnManagePerson = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnManageOrganization = new javax.swing.JButton();
        btnRegister = new javax.swing.JButton();

        btnManagePerson.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnManagePerson.setText("Create Organization Admins");
        btnManagePerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManagePersonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setText("Health Assistant Work Area");

        btnManageOrganization.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnManageOrganization.setText("Create Organization");
        btnManageOrganization.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageOrganizationActionPerformed(evt);
            }
        });

        btnRegister.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnRegister.setText("Register New Patients");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 581, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnManagePerson, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnManageOrganization, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRegister, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(323, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnManageOrganization)
                .addGap(18, 18, 18)
                .addComponent(btnManagePerson)
                .addGap(31, 31, 31)
                .addComponent(btnRegister)
                .addContainerGap(243, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnManagePersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManagePersonActionPerformed
        // TODO add your handling code here:        
        ManagePersonJPanel managePersonJPanel=new ManagePersonJPanel(userProcessContainer,system, enterprise);
        userProcessContainer.add("ManagePersonJPanel", managePersonJPanel);
        CardLayout layout=(CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_btnManagePersonActionPerformed

    private void btnManageOrganizationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageOrganizationActionPerformed
        // TODO add your handling code here:
        ManageOrganizationJPanel manageOrganizationJPanel=new ManageOrganizationJPanel(userProcessContainer,system,enterprise);
        userProcessContainer.add("ManageOrganization", manageOrganizationJPanel);
        CardLayout layout=(CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageOrganizationActionPerformed

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        RegisterPatientsJPanel rpjp=new RegisterPatientsJPanel(userProcessContainer,system,enterprise);
        userProcessContainer.add("ManageOrganization", rpjp);
        CardLayout layout=(CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnRegisterActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnManageOrganization;
    private javax.swing.JButton btnManagePerson;
    private javax.swing.JButton btnRegister;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
